### PR TITLE
Update MSW comparison

### PR DESCRIPTION
**Pull request by kettanaito**
Hey 👋  Once more thanks for including the detailed comparison on the website! As promised, I've published the [Comparison](https://mswjs.io/docs/comparison) page on MSW's side as well. I'd appreciate if you could take a look at that, to make sure the comparison on my side is actual and precise.

## What

These changes update the comparison page of the docs, specifically its comparison with MSW.

## Why

To keep the comparison up-to-date and remove outdated points.

### CODE REVIEW

**Comment by kettanaito** [comment]
> While Mirage and MSW both run in the client alongside your frontend code, the main difference is that MSW runs in a service worker

I find this statement confusing, as MSW doesn't run in a worker, but on a client. It uses the worker for requests interception. Do you think rephrasing would make it more clear?

**Comment by samselikoff** [comment]
Thanks for opening this and again, sorry for the delay in updating the comparison guides!

Is the setup for msw no longer asynchronous? Also, there is still some integration code needed to get it running right?

Could you post the most absolute basic code needed to get msw intercepting a request in the browser, including any separate setup code or files needed?

**Comment by kettanaito** [comment]
Hey, no worries. 

> Is the setup for msw no longer asynchronous?

The setup (Service Worker registration) is still asynchronous, but MSW removes the race condition between it and your application making requests is by deferring any issued request in a timeframe between calling `worker.start()` and Service Worker instance becoming active.

The worker registration time is trivial, and the main reason for this is to ensure consistent behavior by eliminating the race condition.

> Could you post the most absolute basic code needed to get msw intercepting a request in the browser, including any separate setup code or files needed?

Yes, sure. The most basic integration in a browser looks as follows:

1. Copy the worker file:

```bash
$ npx msw init <PUBLIC_DIR>
```

2. Write a mock definition.

```js
// src/mocks.js
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  rest.get('/numbers', (req, res, ctx) => {
    return res(ctx.json([1, 2, 3]))
  })
)

worker.start()
```

Importing the `mocks.js` module in your app will enable the mocking. There are no extra setup steps/files needed.

**Comment by samselikoff** [comment]
> MSW removes the race condition between it and your application making requests is by deferring any issued request in a timeframe between calling worker.start() and Service Worker instance becoming active.

Ah cool! Is this a new feature? I ask because I ran into the issue and had to use the `bootstrap()` logic last time I played with MSW.

And regarding the setup, looks like the worker file is the only significance difference between the projects.

**Comment by kettanaito** [comment]
Yes, the deferring of the requests until the worker is ready is a new feature (from [`0.19.0`](https://github.com/mswjs/msw/releases/tag/v0.19.0), 18 days old), which, I believe, wasn't available yet when you were testing it out. 

> looks like the worker file is the only significance difference between the projects.

Agree, it's a necessary pre-requisite for MSW. I'm treating it as a particular disadvantage, as any other worker-related setups I considered would require even more setup, or be too implicit.

Please, feel free to edit the existing text so the overall comparison reads fluently, as I've just remove the paragraphs that were covered recently (didn't check if it reads nicely). I can help in that too, just let me know the things you'd improve. Thanks!

**Comment by samselikoff** [comment]
https://github.com/miragejs/site/pull/728 fixes

**Pull request closed without merging**
