### PR TITLE
Replace links to faker.js

### PR DESCRIPTION
**Pull request by IanVS**
Now that there's a new official faker.js project, I think it would be good to move the links so that folks aren't sent to the old, broken one.

cc @samselikoff, I know you were bitten by this mess too.  :)

### CODE REVIEW

**Comment by samselikoff** [comment]
@IanVS agree! Looks like some tests are failing which will prevent deploy, if you have time could you look? I believe master is passing but they could be flaky..

**Comment by IanVS** [comment]
@samselikoff It looks like the dependabot PRs are all failing as well, something about sandbox tests in cypress.  There's no way to deploy unless that's fixed?  I don't really have the time to look into those failures, and was hoping for just a quick update to the docs.  :-/

**Comment by samselikoff** [comment]
Right on I'll just deploy manually from netlify 👍  ty for the PR!

**Comment by samselikoff** [comment]
It's live thanks again!

**Pull request merged**
